[2017-12-28 00:30:59] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/subjects/2" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/subjects/2\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/subjects/2\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 00:30:59] application.ERROR: No route found for "GET /api/v1/subjects/2" [] []
[2017-12-28 00:30:59] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 00:30:59] application.DEBUG: < 404 [] []
[2017-12-28 00:31:01] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/subjects/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/subjects/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/subjects/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 00:31:01] application.ERROR: No route found for "GET /api/v1/subjects/1" [] []
[2017-12-28 00:31:01] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 00:31:01] application.DEBUG: < 404 [] []
[2017-12-28 00:31:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/subjects/0" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/subjects/0\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/subjects/0\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 00:31:02] application.ERROR: No route found for "GET /api/v1/subjects/0" [] []
[2017-12-28 00:31:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 00:31:02] application.DEBUG: < 404 [] []
[2017-12-28 00:31:48] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:3000/api/v1/subjects","method":"GET"} []
[2017-12-28 00:31:48] application.DEBUG: > GET /api/v1/subjects [] []
[2017-12-28 00:31:48] application.DEBUG: < 200 [] []
[2017-12-28 00:31:54] application.INFO: Matched route "{route}". {"route":"POST_api_v1_topics","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"POST"} []
[2017-12-28 00:31:54] application.DEBUG: > POST /api/v1/topics [] []
[2017-12-28 00:31:54] application.CRITICAL: RuntimeException: Controller "App\Controllers\TopicsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\TopicsController::save()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 00:31:54] application.ERROR: Controller "App\Controllers\TopicsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 00:31:54] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 00:31:54] application.DEBUG: < 500 [] []
[2017-12-28 00:37:07] application.INFO: Matched route "{route}". {"route":"POST_api_v1_topics","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"POST"} []
[2017-12-28 00:37:07] application.DEBUG: > POST /api/v1/topics [] []
[2017-12-28 00:38:22] application.INFO: Matched route "{route}". {"route":"POST_api_v1_topics","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"POST"} []
[2017-12-28 00:38:22] application.DEBUG: > POST /api/v1/topics [] []
[2017-12-28 00:38:22] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'INSERT INTO topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params ["linguagens", "2"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'INSERT INTO topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [\"linguagens\", \"2\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 00:38:22] application.ERROR: An exception occurred while executing 'INSERT INTO topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params ["linguagens", "2"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist [] []
[2017-12-28 00:38:22] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO top...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO top...', Array, Array) #3 /var/www/html/src/App/Services/TopicsService.php(26): Doctrine\DBAL\Connection->insert('topic', Array) #4 /var/www/html/src/App/Controllers/TopicsController.php(29): App\Services\TopicsService->save(Array) #5 [internal function]: App\Controllers\TopicsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 00:38:22] application.DEBUG: < 500 [] []
[2017-12-28 00:39:37] application.INFO: Matched route "{route}". {"route":"POST_api_v1_topics","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"POST"} []
[2017-12-28 00:39:37] application.DEBUG: > POST /api/v1/topics [] []
[2017-12-28 00:39:37] application.DEBUG: < 200 [] []
[2017-12-28 00:39:42] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics","route_parameters":{"_controller":"topics.controller:getAll","_route":"GET_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"GET"} []
[2017-12-28 00:39:42] application.DEBUG: > GET /api/v1/topics [] []
[2017-12-28 00:39:42] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM topic ':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM topic ':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-12-28 00:39:42] application.ERROR: An exception occurred while executing 'SELECT * FROM topic ':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.topic' doesn't exist [] []
[2017-12-28 00:39:42] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM t...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM t...', Array, Array) #3 /var/www/html/src/App/Services/TopicsService.php(21): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM t...') #4 /var/www/html/src/App/Controllers/TopicsController.php(23): App\Services\TopicsService->getAll() #5 [internal function]: App\Controllers\TopicsController->getAll() #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 00:39:42] application.DEBUG: < 500 [] []
[2017-12-28 00:39:58] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics","route_parameters":{"_controller":"topics.controller:getAll","_route":"GET_api_v1_topics"},"request_uri":"http://localhost:3000/api/v1/topics","method":"GET"} []
[2017-12-28 00:39:58] application.DEBUG: > GET /api/v1/topics [] []
[2017-12-28 00:39:58] application.DEBUG: < 200 [] []
[2017-12-28 00:40:03] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"1","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/1","method":"GET"} []
[2017-12-28 00:40:03] application.DEBUG: > GET /api/v1/topics/1 [] []
[2017-12-28 00:40:03] application.CRITICAL: RuntimeException: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\TopicsController::getBySubject()\" requires that you provide a value for the \"$subject\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 00:40:03] application.ERROR: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 00:40:03] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 00:40:03] application.DEBUG: < 500 [] []
[2017-12-28 00:40:12] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:40:12] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:40:12] application.CRITICAL: RuntimeException: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\TopicsController::getBySubject()\" requires that you provide a value for the \"$subject\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 00:40:12] application.ERROR: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 00:40:12] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 00:40:12] application.DEBUG: < 500 [] []
[2017-12-28 00:43:16] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:43:16] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:43:16] application.CRITICAL: RuntimeException: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\TopicsController::getBySubject()\" requires that you provide a value for the \"$subject\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 00:43:16] application.ERROR: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 00:43:16] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 00:43:16] application.DEBUG: < 500 [] []
[2017-12-28 00:43:46] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:43:46] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:43:46] application.CRITICAL: RuntimeException: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\TopicsController::getBySubject()\" requires that you provide a value for the \"$subject\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 00:43:46] application.ERROR: Controller "App\Controllers\TopicsController::getBySubject()" requires that you provide a value for the "$subject" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 00:43:46] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 00:43:46] application.DEBUG: < 500 [] []
[2017-12-28 00:44:11] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:44:11] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:44:11] application.DEBUG: < 200 [] []
[2017-12-28 00:44:17] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"1","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/1","method":"GET"} []
[2017-12-28 00:44:17] application.DEBUG: > GET /api/v1/topics/1 [] []
[2017-12-28 00:44:17] application.DEBUG: < 200 [] []
[2017-12-28 00:44:18] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:44:18] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:44:18] application.DEBUG: < 200 [] []
[2017-12-28 00:44:19] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"3","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/3","method":"GET"} []
[2017-12-28 00:44:19] application.DEBUG: > GET /api/v1/topics/3 [] []
[2017-12-28 00:44:19] application.DEBUG: < 200 [] []
[2017-12-28 00:44:20] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"4","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/4","method":"GET"} []
[2017-12-28 00:44:20] application.DEBUG: > GET /api/v1/topics/4 [] []
[2017-12-28 00:44:20] application.DEBUG: < 200 [] []
[2017-12-28 00:44:21] application.INFO: Matched route "{route}". {"route":"GET_api_v1_topics_subject_id","route_parameters":{"_controller":"topics.controller:getBySubject","subject_id":"2","_route":"GET_api_v1_topics_subject_id"},"request_uri":"http://localhost:3000/api/v1/topics/2","method":"GET"} []
[2017-12-28 00:44:21] application.DEBUG: > GET /api/v1/topics/2 [] []
[2017-12-28 00:44:21] application.DEBUG: < 200 [] []
[2017-12-28 14:01:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 14:01:45] application.ERROR: No route found for "GET /" [] []
[2017-12-28 14:01:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 14:01:45] application.DEBUG: < 404 [] []
[2017-12-28 14:02:04] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 14:02:04] application.ERROR: No route found for "GET /" [] []
[2017-12-28 14:02:04] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 14:02:04] application.DEBUG: < 404 [] []
[2017-12-28 14:02:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /teste" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /teste\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/teste\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 14:02:27] application.ERROR: No route found for "GET /teste" [] []
[2017-12-28 14:02:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 14:02:27] application.DEBUG: < 404 [] []
[2017-12-28 14:02:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /subjects" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /subjects\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/subjects\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 14:02:45] application.ERROR: No route found for "GET /subjects" [] []
[2017-12-28 14:02:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 14:02:45] application.DEBUG: < 404 [] []
[2017-12-28 14:03:06] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://192.168.1.109:3000/api/v1/subjects","method":"GET"} []
[2017-12-28 14:03:06] application.DEBUG: > GET /api/v1/subjects [] []
[2017-12-28 14:03:06] application.DEBUG: < 200 [] []
[2017-12-28 15:02:23] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/problem" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/problem\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problem\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 15:02:23] application.ERROR: No route found for "POST /api/v1/problem" [] []
[2017-12-28 15:02:23] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:02:23] application.DEBUG: < 404 [] []
[2017-12-28 15:02:43] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/problems" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/problems\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 15:02:43] application.ERROR: No route found for "POST /api/v1/problems" [] []
[2017-12-28 15:02:43] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:02:43] application.DEBUG: < 404 [] []
[2017-12-28 15:03:14] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:3000/api/v1/subjects","method":"GET"} []
[2017-12-28 15:03:14] application.DEBUG: > GET /api/v1/subjects [] []
[2017-12-28 15:03:14] application.DEBUG: < 200 [] []
[2017-12-28 15:03:21] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/problems" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/problems\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 15:03:21] application.ERROR: No route found for "POST /api/v1/problems" [] []
[2017-12-28 15:03:21] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:03:21] application.DEBUG: < 404 [] []
[2017-12-28 15:03:38] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:03:38] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:03:39] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:03:39] application.ERROR: An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null [] []
[2017-12-28 15:03:39] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/TopicsService.php(26): Doctrine\DBAL\Connection->insert('problem_topic', Array) #4 /var/www/html/src/App/Controllers/TopicsController.php(29): App\Services\TopicsService->save(Array) #5 [internal function]: App\Controllers\TopicsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:03:39] application.DEBUG: < 500 [] []
[2017-12-28 15:04:15] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"topics.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:04:15] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:04:15] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:04:15] application.ERROR: An exception occurred while executing 'INSERT INTO problem_topic (topic_name, topic_subject_subject_id) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'topic_name' cannot be null [] []
[2017-12-28 15:04:15] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/TopicsService.php(26): Doctrine\DBAL\Connection->insert('problem_topic', Array) #4 /var/www/html/src/App/Controllers/TopicsController.php(29): App\Services\TopicsService->save(Array) #5 [internal function]: App\Controllers\TopicsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:04:15] application.DEBUG: < 500 [] []
[2017-12-28 15:04:59] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:04:59] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:04:59] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::save()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 15:04:59] application.ERROR: Controller "App\Controllers\ProblemsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 15:04:59] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 15:04:59] application.DEBUG: < 500 [] []
[2017-12-28 15:21:53] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:21:53] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:21:53] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::save()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 15:21:53] application.ERROR: Controller "App\Controllers\ProblemsController::save()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 15:21:53] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 15:21:53] application.DEBUG: < 500 [] []
[2017-12-28 15:24:00] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:24:00] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:24:01] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO check (check_description) VALUES (?)' with params ["assinale a alternativa correta"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check (check_description) VALUES ('assinale a alternativa correta')' at line 1 (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO check (check_description) VALUES (?)' with params [\"assinale a alternativa correta\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check (check_description) VALUES ('assinale a alternativa correta')' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check (check_description) VALUES ('assinale a alternativa correta')' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check (check_description) VALUES ('assinale a alternativa correta')' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:24:01] application.ERROR: An exception occurred while executing 'INSERT INTO check (check_description) VALUES (?)' with params ["assinale a alternativa correta"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check (check_description) VALUES ('assinale a alternativa correta')' at line 1 [] []
[2017-12-28 15:24:01] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO che...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO che...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(39): Doctrine\DBAL\Connection->insert('check', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\ProblemsService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:24:01] application.DEBUG: < 500 [] []
[2017-12-28 15:35:07] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:35:07] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:41:29] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:41:29] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:43:19] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:43:19] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:43:20] application.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_difficulty, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params ["problem", null, "2", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_difficulty' in 'field list' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO problem (problem_name, problem_difficulty, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params [\"problem\", null, \"2\", null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_difficulty' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_difficulty' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_difficulty' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:43:20] application.ERROR: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_difficulty, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params ["problem", null, "2", null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_difficulty' in 'field list' [] []
[2017-12-28 15:43:20] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(54): Doctrine\DBAL\Connection->insert('problem', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\ProblemsService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:43:20] application.DEBUG: < 500 [] []
[2017-12-28 15:44:12] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:44:12] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:44:13] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params ["problem", "4", null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_topic_topic_id' cannot be null (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params [\"problem\", \"4\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_topic_topic_id' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_topic_topic_id' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_topic_topic_id' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:44:13] application.ERROR: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params ["problem", "4", null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_topic_topic_id' cannot be null [] []
[2017-12-28 15:44:13] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(54): Doctrine\DBAL\Connection->insert('problem', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\ProblemsService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:44:13] application.DEBUG: < 500 [] []
[2017-12-28 15:45:02] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:45:02] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:45:02] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params ["problem", "6", "2"]:  SQLSTATE[HY000]: General error: 1364 Field 'problem_type' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params [\"problem\", \"6\", \"2\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'problem_type' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'problem_type' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'problem_type' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:45:02] application.ERROR: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?)' with params ["problem", "6", "2"]:  SQLSTATE[HY000]: General error: 1364 Field 'problem_type' doesn't have a default value [] []
[2017-12-28 15:45:02] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(54): Doctrine\DBAL\Connection->insert('problem', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\ProblemsService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:45:02] application.DEBUG: < 500 [] []
[2017-12-28 15:46:17] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:46:17] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:46:17] application.CRITICAL: Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params ["problem", "0", "8", "2"]:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mydb`.`problem`, CONSTRAINT `fk_problem_problem_topic1` FOREIGN KEY (`problem_topic_topic_id`) REFERENCES `problem_topic` (`topic_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params [\"problem\", \"0\", \"8\", \"2\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mydb`.`problem`, CONSTRAINT `fk_problem_problem_topic1` FOREIGN KEY (`problem_topic_topic_id`) REFERENCES `problem_topic` (`topic_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mydb`.`problem`, CONSTRAINT `fk_problem_problem_topic1` FOREIGN KEY (`problem_topic_topic_id`) REFERENCES `problem_topic` (`topic_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mydb`.`problem`, CONSTRAINT `fk_problem_problem_topic1` FOREIGN KEY (`problem_topic_topic_id`) REFERENCES `problem_topic` (`topic_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:46:17] application.ERROR: An exception occurred while executing 'INSERT INTO problem (problem_name, problem_type, problem_type_id, problem_topic_topic_id) VALUES (?, ?, ?, ?)' with params ["problem", "0", "8", "2"]:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mydb`.`problem`, CONSTRAINT `fk_problem_problem_topic1` FOREIGN KEY (`problem_topic_topic_id`) REFERENCES `problem_topic` (`topic_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) [] []
[2017-12-28 15:46:17] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO pro...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO pro...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(55): Doctrine\DBAL\Connection->insert('problem', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\ProblemsService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:46:17] application.DEBUG: < 500 [] []
[2017-12-28 15:46:49] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 15:46:49] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 15:46:49] application.DEBUG: < 200 [] []
[2017-12-28 15:47:10] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "GET /api/v1/problems": Method Not Allowed (Allow: POST, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /api/v1/problems\": Method Not Allowed (Allow: POST, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-28 15:47:10] application.ERROR: No route found for "GET /api/v1/problems": Method Not Allowed (Allow: POST, OPTIONS) [] []
[2017-12-28 15:47:10] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:47:10] application.DEBUG: < 405 [] []
[2017-12-28 15:47:16] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_topics_id","route_parameters":{"_controller":"problems.controller:getOne","topics_id":"1","_route":"GET_api_v1_problems_topics_id"},"request_uri":"http://localhost:3000/api/v1/problems/1","method":"GET"} []
[2017-12-28 15:47:16] application.DEBUG: > GET /api/v1/problems/1 [] []
[2017-12-28 15:47:16] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getOne()" requires that you provide a value for the "$id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getOne()\" requires that you provide a value for the \"$id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 15:47:16] application.ERROR: Controller "App\Controllers\ProblemsController::getOne()" requires that you provide a value for the "$id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 15:47:16] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 15:47:16] application.DEBUG: < 500 [] []
[2017-12-28 15:51:09] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/problems/1": Method Not Allowed (Allow: GET, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/problems/1\": Method Not Allowed (Allow: GET, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-28 15:51:09] application.ERROR: No route found for "POST /api/v1/problems/1": Method Not Allowed (Allow: GET, OPTIONS) [] []
[2017-12-28 15:51:09] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:51:09] application.DEBUG: < 405 [] []
[2017-12-28 15:51:16] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/problems/2": Method Not Allowed (Allow: GET, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/problems/2\": Method Not Allowed (Allow: GET, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-28 15:51:16] application.ERROR: No route found for "POST /api/v1/problems/2": Method Not Allowed (Allow: GET, OPTIONS) [] []
[2017-12-28 15:51:16] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 15:51:16] application.DEBUG: < 405 [] []
[2017-12-28 15:51:20] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_problems_id","route_parameters":{"_controller":"problems.controller:getOne","problems_id":"2","_route":"GET_api_v1_problems_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 15:51:20] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 15:51:20] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getOne()" requires that you provide a value for the "$id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getOne()\" requires that you provide a value for the \"$id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2017-12-28 15:51:20] application.ERROR: Controller "App\Controllers\ProblemsController::getOne()" requires that you provide a value for the "$id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2017-12-28 15:51:20] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2017-12-28 15:51:20] application.DEBUG: < 500 [] []
[2017-12-28 15:52:07] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 15:52:07] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 15:52:07] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT * FROM check WHERE check_id=?' with params [10]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check WHERE check_id='10'' at line 1 (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT * FROM check WHERE check_id=?' with params [10]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check WHERE check_id='10'' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check WHERE check_id='10'' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check WHERE check_id='10'' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 15:52:07] application.ERROR: An exception occurred while executing 'SELECT * FROM check WHERE check_id=?' with params [10]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'check WHERE check_id='10'' at line 1 [] []
[2017-12-28 15:52:07] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM c...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM c...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(20): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM c...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('2') #5 [internal function]: App\Controllers\ProblemsController->getOne('2') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 15:52:07] application.DEBUG: < 500 [] []
[2017-12-28 15:54:18] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 15:54:18] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 15:54:18] application.DEBUG: < 200 [] []
[2017-12-28 15:57:04] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 15:57:04] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 15:57:04] application.DEBUG: < 200 [] []
[2017-12-28 16:00:41] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 16:00:41] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 16:00:42] application.DEBUG: < 200 [] []
[2017-12-28 16:03:27] application.INFO: Matched route "{route}". {"route":"POST_api_v1_problems","route_parameters":{"_controller":"problems.controller:save","_route":"POST_api_v1_problems"},"request_uri":"http://localhost:3000/api/v1/problems","method":"POST"} []
[2017-12-28 16:03:27] application.DEBUG: > POST /api/v1/problems [] []
[2017-12-28 16:03:28] application.DEBUG: < 200 [] []
[2017-12-28 16:03:34] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"4","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/4","method":"GET"} []
[2017-12-28 16:03:34] application.DEBUG: > GET /api/v1/problems/4 [] []
[2017-12-28 16:03:34] application.DEBUG: < 200 [] []
[2017-12-28 16:03:43] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"3","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/3","method":"GET"} []
[2017-12-28 16:03:43] application.DEBUG: > GET /api/v1/problems/3 [] []
[2017-12-28 16:03:43] application.DEBUG: < 200 [] []
[2017-12-28 16:03:45] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 16:03:45] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 16:03:45] application.DEBUG: < 200 [] []
[2017-12-28 16:03:52] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"4","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/4","method":"GET"} []
[2017-12-28 16:03:52] application.DEBUG: > GET /api/v1/problems/4 [] []
[2017-12-28 16:03:52] application.DEBUG: < 200 [] []
[2017-12-28 16:03:54] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"3","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/3","method":"GET"} []
[2017-12-28 16:03:54] application.DEBUG: > GET /api/v1/problems/3 [] []
[2017-12-28 16:03:54] application.DEBUG: < 200 [] []
[2017-12-28 16:03:56] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 16:03:56] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 16:03:56] application.DEBUG: < 200 [] []
[2017-12-28 16:03:57] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"1","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/1","method":"GET"} []
[2017-12-28 16:03:57] application.DEBUG: > GET /api/v1/problems/1 [] []
[2017-12-28 16:03:58] application.DEBUG: < 200 [] []
[2017-12-28 16:03:59] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"2","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/2","method":"GET"} []
[2017-12-28 16:03:59] application.DEBUG: > GET /api/v1/problems/2 [] []
[2017-12-28 16:03:59] application.DEBUG: < 200 [] []
[2017-12-28 16:04:02] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"4","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/4","method":"GET"} []
[2017-12-28 16:04:02] application.DEBUG: > GET /api/v1/problems/4 [] []
[2017-12-28 16:04:02] application.DEBUG: < 200 [] []
[2017-12-28 16:05:40] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"4","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:3000/api/v1/problems/4","method":"GET"} []
[2017-12-28 16:05:40] application.DEBUG: > GET /api/v1/problems/4 [] []
[2017-12-28 16:05:40] application.DEBUG: < 200 [] []
[2017-12-28 17:29:20] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/users": Method Not Allowed (Allow: GET, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/users\": Method Not Allowed (Allow: GET, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-28 17:29:20] application.ERROR: No route found for "POST /api/v1/users": Method Not Allowed (Allow: GET, OPTIONS) [] []
[2017-12-28 17:29:20] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 17:29:20] application.DEBUG: < 405 [] []
[2017-12-28 17:29:59] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 17:29:59] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 17:30:51] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 17:30:51] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 17:30:51] application.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO user_student (problem_name, problem_difficulty, problem_type, problem_topic_topic_id, check_description, item) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_name' in 'field list' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO user_student (problem_name, problem_difficulty, problem_type, problem_topic_topic_id, check_description, item) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_name' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_name' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_name' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 17:30:51] application.ERROR: An exception occurred while executing 'INSERT INTO user_student (problem_name, problem_difficulty, problem_type, problem_topic_topic_id, check_description, item) VALUES (?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'problem_name' in 'field list' [] []
[2017-12-28 17:30:51] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO use...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO use...', Array, Array) #3 /var/www/html/src/App/Services/UsersService.php(22): Doctrine\DBAL\Connection->insert('user_student', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(30): App\Services\UsersService->save(Array) #5 [internal function]: App\Controllers\ProblemsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 17:30:51] application.DEBUG: < 500 [] []
[2017-12-28 17:32:04] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 17:32:04] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 17:32:04] application.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO user_student (user_cpf, user_name, user_last_name, user_email, user_password, user_token) VALUES (?, ?, ?, ?, ?, ?)' with params ["293829", "renan", "kawamura", "renanyk78@gmail.com", "123456", "b77e3d9dd8958f2c3f8cac8b13a49774"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_cpf' in 'field list' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO user_student (user_cpf, user_name, user_last_name, user_email, user_password, user_token) VALUES (?, ?, ?, ?, ?, ?)' with params [\"293829\", \"renan\", \"kawamura\", \"renanyk78@gmail.com\", \"123456\", \"b77e3d9dd8958f2c3f8cac8b13a49774\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_cpf' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_cpf' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_cpf' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-28 17:32:04] application.ERROR: An exception occurred while executing 'INSERT INTO user_student (user_cpf, user_name, user_last_name, user_email, user_password, user_token) VALUES (?, ?, ?, ?, ?, ?)' with params ["293829", "renan", "kawamura", "renanyk78@gmail.com", "123456", "b77e3d9dd8958f2c3f8cac8b13a49774"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_cpf' in 'field list' [] []
[2017-12-28 17:32:04] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO use...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO use...', Array, Array) #3 /var/www/html/src/App/Services/UsersService.php(22): Doctrine\DBAL\Connection->insert('user_student', Array) #4 /var/www/html/src/App/Controllers/UsersController.php(44): App\Services\UsersService->save(Array) #5 [internal function]: App\Controllers\UsersController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-28 17:32:04] application.DEBUG: < 500 [] []
[2017-12-28 17:34:23] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 17:34:23] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 17:34:23] application.DEBUG: < 200 [] []
[2017-12-28 17:39:49] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 17:39:49] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 17:39:49] application.CRITICAL: Doctrine\DBAL\DBALException: Unknown column type "" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 240 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): Unknown column type \"\" requested. Any Doctrine type that you use has to be registered with \\Doctrine\\DBAL\\Types\\Type::addType(). You can get a list of all the known types with \\Doctrine\\DBAL\\Types\\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:240)"} []
[2017-12-28 17:39:49] application.ERROR: Unknown column type "" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. [] []
[2017-12-28 17:39:49] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php(172): Doctrine\DBAL\DBALException::unknownColumnType('') #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1501): Doctrine\DBAL\Types\Type::getType('') #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1537): Doctrine\DBAL\Connection->getBindingInfo('', '') #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\Connection->resolveParams(Array, Array) #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM u...', Array, Array) #5 /var/www/html/src/App/Services/UsersService.php(16): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM u...', Array, Array) #6 /var/www/html/src/App/Controllers/UsersController.php(24): App\Services\UsersService->signIn(Array) #7 [internal function]: App\Controllers\UsersController->signIn(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-28 17:39:49] application.DEBUG: < 500 [] []
[2017-12-28 17:41:37] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 17:41:37] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 17:41:37] application.DEBUG: < 200 [] []
[2017-12-28 17:54:33] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 17:54:33] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 17:54:33] application.DEBUG: < 200 [] []
[2017-12-28 17:55:53] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 17:55:53] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 17:55:53] application.DEBUG: < 200 [] []
[2017-12-28 18:04:35] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:04:35] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:07:29] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:07:29] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:07:29] application.DEBUG: < 200 [] []
[2017-12-28 18:11:20] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:11:20] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:11:20] application.DEBUG: < 200 [] []
[2017-12-28 18:11:32] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:11:32] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:11:32] application.DEBUG: < 200 [] []
[2017-12-28 18:11:37] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 18:11:37] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 18:11:37] application.DEBUG: < 200 [] []
[2017-12-28 18:11:49] application.INFO: Matched route "{route}". {"route":"POST_api_v1_users","route_parameters":{"_controller":"users.controller:save","_route":"POST_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"POST"} []
[2017-12-28 18:11:49] application.DEBUG: > POST /api/v1/users [] []
[2017-12-28 18:11:49] application.DEBUG: < 200 [] []
[2017-12-28 18:12:10] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:12:10] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:12:10] application.DEBUG: < 200 [] []
[2017-12-28 18:13:26] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:13:26] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:19:16] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:19:16] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:19:16] application.DEBUG: < 200 [] []
[2017-12-28 18:21:27] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:21:27] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:21:27] application.DEBUG: < 200 [] []
[2017-12-28 18:23:09] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:23:09] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:23:09] application.DEBUG: < 200 [] []
[2017-12-28 18:23:25] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:23:25] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:23:25] application.DEBUG: < 200 [] []
[2017-12-28 18:27:18] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:27:18] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:27:18] application.DEBUG: < 200 [] []
[2017-12-28 18:28:23] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:28:23] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:28:23] application.DEBUG: < 200 [] []
[2017-12-28 18:28:35] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:28:35] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:28:35] application.DEBUG: < 200 [] []
[2017-12-28 18:28:41] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users","route_parameters":{"_controller":"users.controller:signIn","_route":"PUT_api_v1_users"},"request_uri":"http://localhost:3000/api/v1/users","method":"PUT"} []
[2017-12-28 18:28:41] application.DEBUG: > PUT /api/v1/users [] []
[2017-12-28 18:28:41] application.DEBUG: < 200 [] []
[2017-12-28 18:40:26] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users_id","route_parameters":{"_controller":"users.controller:signOut","id":"1","_route":"PUT_api_v1_users_id"},"request_uri":"http://localhost:3000/api/v1/users/1","method":"PUT"} []
[2017-12-28 18:40:26] application.DEBUG: > PUT /api/v1/users/1 [] []
[2017-12-28 18:41:30] application.INFO: Matched route "{route}". {"route":"PUT_api_v1_users_id","route_parameters":{"_controller":"users.controller:signOut","id":"1","_route":"PUT_api_v1_users_id"},"request_uri":"http://localhost:3000/api/v1/users/1","method":"PUT"} []
[2017-12-28 18:41:30] application.DEBUG: > PUT /api/v1/users/1 [] []
[2017-12-28 18:41:31] application.DEBUG: < 200 [] []
[2017-12-28 22:54:37] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-28 22:54:37] application.ERROR: No route found for "GET /" [] []
[2017-12-28 22:54:37] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-28 22:54:37] application.DEBUG: < 404 [] []
