[2017-12-24 00:24:15] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:24:15] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:24:15] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM n...') #6 /var/www/html/src/App/Controllers/NotesController.php(26): App\Services\NotesService->getAll() #7 [internal function]: App\Controllers\NotesController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:24:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/teste" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/teste\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/teste\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:24:45] application.ERROR: No route found for "GET /api/v1/teste" [] []
[2017-12-24 00:24:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:24:49] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:24:49] application.ERROR: No route found for "GET /api/v1/1" [] []
[2017-12-24 00:24:49] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:24:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:24:53] application.ERROR: No route found for "GET /api/v1/" [] []
[2017-12-24 00:24:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:25:37] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:25:37] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:25:37] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('1') #7 [internal function]: App\Controllers\NotesController->getOne('1') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:26:05] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:26:05] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:26:05] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('2') #7 [internal function]: App\Controllers\NotesController->getOne('2') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:26:09] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:26:09] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:26:09] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('13') #7 [internal function]: App\Controllers\NotesController->getOne('13') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:26:17] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:26:17] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:26:17] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM n...') #6 /var/www/html/src/App/Controllers/NotesController.php(26): App\Services\NotesService->getAll() #7 [internal function]: App\Controllers\NotesController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:26:24] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:26:24] application.ERROR: No route found for "GET /api/v1/note" [] []
[2017-12-24 00:26:24] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:26:30] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:26:30] application.ERROR: No route found for "GET /api/v1/note/1" [] []
[2017-12-24 00:26:30] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:27:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note/21" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note/21\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note/21\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:27:35] application.ERROR: No route found for "GET /api/v1/note/21" [] []
[2017-12-24 00:27:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:27:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:27:41] application.ERROR: No route found for "GET /api/v1/note/1" [] []
[2017-12-24 00:27:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:28:08] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:28:08] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:28:08] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('1') #7 [internal function]: App\Controllers\NotesController->getOne('1') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:28:49] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:28:49] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:28:49] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('2') #7 [internal function]: App\Controllers\NotesController->getOne('2') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:28:58] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:28:58] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:28:58] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('3') #7 [internal function]: App\Controllers\NotesController->getOne('3') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:30:11] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:30:11] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:30:11] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('3') #7 [internal function]: App\Controllers\NotesController->getOne('3') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:30:19] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:30:19] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:30:19] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('2') #7 [internal function]: App\Controllers\NotesController->getOne('2') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:30:21] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 85 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occured in driver: could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:30:21] application.ERROR: An exception occured in driver: could not find driver [] []
[2017-12-24 00:30:21] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php(62): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOSqlite\Driver->connect(Array, 'root', NULL, Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM n...') #6 /var/www/html/src/App/Controllers/NotesController.php(26): App\Services\NotesService->getAll() #7 [internal function]: App\Controllers\NotesController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:40:12] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:40:12] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 00:40:12] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('3') #7 [internal function]: App\Controllers\NotesController->getOne('3') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:40:26] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:40:26] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 00:40:26] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 00:47:37] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:47:37] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 00:47:37] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM n...') #6 /var/www/html/src/App/Controllers/NotesController.php(26): App\Services\NotesService->getAll() #7 [internal function]: App\Controllers\NotesController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:56:45] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 00:56:45] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 00:56:45] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(15): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM n...') #6 /var/www/html/src/App/Controllers/NotesController.php(26): App\Services\NotesService->getAll() #7 [internal function]: App\Controllers\NotesController->getAll() #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 00:59:08] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 00:59:08] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 00:59:08] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 01:01:52] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 01:01:52] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 01:01:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 01:02:23] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 01:02:23] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 01:02:23] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('1') #7 [internal function]: App\Controllers\NotesController->getOne('1') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 01:02:23] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/3213/2" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/3213/2\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/3213/2\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 01:02:23] application.ERROR: No route found for "GET /api/v1/3213/2" [] []
[2017-12-24 01:02:23] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 01:02:39] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 01:02:39] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 01:02:39] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('2') #7 [internal function]: App\Controllers\NotesController->getOne('2') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 01:04:12] application.CRITICAL: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-12-24 01:04:12] application.ERROR: An exception occured in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known [] []
[2017-12-24 01:04:12] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(47): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException)) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'kawamura', Array) #3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): Doctrine\DBAL\Connection->connect() #4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM n...', Array, Array) #5 /var/www/html/src/App/Services/NotesService.php(10): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM n...', Array) #6 /var/www/html/src/App/Controllers/NotesController.php(21): App\Services\NotesService->getOne('1') #7 [internal function]: App\Controllers\NotesController->getOne('1') #8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #14 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #15 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #16 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #17 {main} [] []
[2017-12-24 01:20:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 01:20:35] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 01:20:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 01:20:40] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 01:20:40] application.ERROR: No route found for "GET /api/v1/note" [] []
[2017-12-24 01:20:40] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 01:20:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note2" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note2\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note2\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 01:20:45] application.ERROR: No route found for "GET /api/v1/note2" [] []
[2017-12-24 01:20:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:06:22] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/note2" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/note2\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note2\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 02:06:22] application.ERROR: No route found for "GET /api/v1/note2" [] []
[2017-12-24 02:06:22] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:17:30] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-24 02:17:30] application.ERROR: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note [] []
[2017-12-24 02:17:30] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO not...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO not...', Array, Array) #3 /var/www/html/src/App/Services/NotesService.php(20): Doctrine\DBAL\Connection->insert('notes', Array) #4 /var/www/html/src/App/Controllers/NotesController.php(33): App\Services\NotesService->save(Array) #5 [internal function]: App\Controllers\NotesController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-24 02:19:55] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-24 02:19:55] application.ERROR: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note [] []
[2017-12-24 02:19:55] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO not...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO not...', Array, Array) #3 /var/www/html/src/App/Services/NotesService.php(20): Doctrine\DBAL\Connection->insert('notes', Array) #4 /var/www/html/src/App/Controllers/NotesController.php(33): App\Services\NotesService->save(Array) #5 [internal function]: App\Controllers\NotesController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-24 02:21:24] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-24 02:21:24] application.ERROR: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note [] []
[2017-12-24 02:21:24] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO not...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO not...', Array, Array) #3 /var/www/html/src/App/Services/NotesService.php(20): Doctrine\DBAL\Connection->insert('notes', Array) #4 /var/www/html/src/App/Controllers/NotesController.php(33): App\Services\NotesService->save(Array) #5 [internal function]: App\Controllers\NotesController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-24 02:21:40] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-24 02:21:40] application.ERROR: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note [] []
[2017-12-24 02:21:40] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO not...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO not...', Array, Array) #3 /var/www/html/src/App/Services/NotesService.php(20): Doctrine\DBAL\Connection->insert('notes', Array) #4 /var/www/html/src/App/Controllers/NotesController.php(33): App\Services\NotesService->save(Array) #5 [internal function]: App\Controllers\NotesController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-24 02:22:02] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 54 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-12-24 02:22:02] application.ERROR: An exception occurred while executing 'INSERT INTO notes (note) VALUES (?)' with params [null]:  SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: notes.note [] []
[2017-12-24 02:22:02] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO not...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO not...', Array, Array) #3 /var/www/html/src/App/Services/NotesService.php(20): Doctrine\DBAL\Connection->insert('notes', Array) #4 /var/www/html/src/App/Controllers/NotesController.php(33): App\Services\NotesService->save(Array) #5 [internal function]: App\Controllers\NotesController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2017-12-24 02:22:11] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/notes/1": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/notes/1\": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-24 02:22:11] application.ERROR: No route found for "POST /api/v1/notes/1": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) [] []
[2017-12-24 02:22:11] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:22:16] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/note" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/note\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 02:22:16] application.ERROR: No route found for "POST /api/v1/note" [] []
[2017-12-24 02:22:16] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:22:19] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/note/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/note/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/note/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 02:22:19] application.ERROR: No route found for "POST /api/v1/note/1" [] []
[2017-12-24 02:22:19] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:22:23] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /api/v1/notes/3": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /api/v1/notes/3\": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-12-24 02:22:23] application.ERROR: No route found for "POST /api/v1/notes/3": Method Not Allowed (Allow: GET, PUT, DELETE, OPTIONS) [] []
[2017-12-24 02:22:23] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:22:36] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 02:22:36] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 02:22:36] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2017-12-24 02:22:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/notes/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/notes/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/notes/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-12-24 02:22:45] application.ERROR: No route found for "GET /api/v1/notes/" [] []
[2017-12-24 02:22:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
