[2018-01-09 01:01:52] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/subject/1/topic/1/type/1" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/subject/1/topic/1/type/1\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/subject/1/topic/1/type/1\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:01:52] application.ERROR: No route found for "GET /api/v1//problems/subject/1/topic/1/type/1" [] []
[2018-01-09 01:01:52] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:01:52] application.DEBUG: < 404 [] []
[2018-01-09 01:02:11] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/subject/1/topic/1/type/1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/subject/1/topic/1/type/1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/subject/1/topic/1/type/1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:02:11] application.ERROR: No route found for "GET /api/v1//problems/subject/1/topic/1/type/1/" [] []
[2018-01-09 01:02:11] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:02:11] application.DEBUG: < 404 [] []
[2018-01-09 01:04:30] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:04:30] application.ERROR: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:04:30] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:04:30] application.DEBUG: < 404 [] []
[2018-01-09 01:04:44] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:04:44] application.ERROR: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:04:44] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:04:44] application.DEBUG: < 404 [] []
[2018-01-09 01:04:45] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:04:45] application.ERROR: No route found for "GET /api/v1//problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:04:45] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:04:45] application.DEBUG: < 404 [] []
[2018-01-09 01:06:57] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:06:57] application.ERROR: No route found for "GET /api/v1//problems/" [] []
[2018-01-09 01:06:57] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:06:57] application.DEBUG: < 404 [] []
[2018-01-09 01:07:02] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1//problems" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1//problems\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1//problems\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:07:02] application.ERROR: No route found for "GET /api/v1//problems" [] []
[2018-01-09 01:07:02] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:07:02] application.DEBUG: < 404 [] []
[2018-01-09 01:07:11] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:07:11] application.ERROR: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:07:11] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:07:11] application.DEBUG: < 404 [] []
[2018-01-09 01:07:20] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type/1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type/1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:07:20] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" [] []
[2018-01-09 01:07:20] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:07:20] application.DEBUG: < 404 [] []
[2018-01-09 01:07:23] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems","route_parameters":{"_controller":"problems.controller:getAll","_route":"GET_api_v1_problems"},"request_uri":"http://localhost:9001/api/v1/problems","method":"GET"} []
[2018-01-09 01:07:23] application.DEBUG: > GET /api/v1/problems [] []
[2018-01-09 01:07:24] application.DEBUG: < 200 [] []
[2018-01-09 01:07:30] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"1","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/1","method":"GET"} []
[2018-01-09 01:07:30] application.DEBUG: > GET /api/v1/problems/1 [] []
[2018-01-09 01:07:30] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:07:30] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:07:30] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('1') #5 [internal function]: App\Controllers\ProblemsController->getOne('1') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:07:30] application.DEBUG: < 500 [] []
[2018-01-09 01:07:37] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"{1}","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/%7B1%7D","method":"GET"} []
[2018-01-09 01:07:37] application.DEBUG: > GET /api/v1/problems/%7B1%7D [] []
[2018-01-09 01:07:37] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:07:37] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:07:37] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('{1}') #5 [internal function]: App\Controllers\ProblemsController->getOne('{1}') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:07:37] application.DEBUG: < 500 [] []
[2018-01-09 01:08:20] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"{1}","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/%7B1%7D","method":"GET"} []
[2018-01-09 01:08:20] application.DEBUG: > GET /api/v1/problems/%7B1%7D [] []
[2018-01-09 01:08:20] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:08:20] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:08:20] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('{1}') #5 [internal function]: App\Controllers\ProblemsController->getOne('{1}') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:08:20] application.DEBUG: < 500 [] []
[2018-01-09 01:08:26] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subjects","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subjects","method":"GET"} []
[2018-01-09 01:08:26] application.DEBUG: > GET /api/v1/problems/subjects [] []
[2018-01-09 01:08:26] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:08:26] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:08:26] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subjects') #5 [internal function]: App\Controllers\ProblemsController->getOne('subjects') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:08:26] application.DEBUG: < 500 [] []
[2018-01-09 01:08:42] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:08:42] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:08:42] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:08:42] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:08:42] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:08:42] application.DEBUG: < 500 [] []
[2018-01-09 01:09:01] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:09:01] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:09:01] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:09:01] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:09:01] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:09:01] application.DEBUG: < 500 [] []
[2018-01-09 01:09:02] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:09:02] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:09:02] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:09:02] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:09:02] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:09:02] application.DEBUG: < 500 [] []
[2018-01-09 01:09:02] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:09:02] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:09:02] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:09:02] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:09:02] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:09:02] application.DEBUG: < 500 [] []
[2018-01-09 01:09:09] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:09:09] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:09:09] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:09:09] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:09:09] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:09:09] application.DEBUG: < 500 [] []
[2018-01-09 01:09:11] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_id","route_parameters":{"_controller":"problems.controller:getOne","id":"subject","_route":"GET_api_v1_problems_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject","method":"GET"} []
[2018-01-09 01:09:11] application.DEBUG: > GET /api/v1/problems/subject [] []
[2018-01-09 01:09:11] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 01:09:11] application.ERROR: An exception occurred while executing 'SELECT * FROM item WHERE check_check_id=?' with params [0]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.item' doesn't exist [] []
[2018-01-09 01:09:11] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM i...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM i...', Array, Array) #3 /var/www/html/src/App/Services/ProblemsService.php(40): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM i...', Array) #4 /var/www/html/src/App/Controllers/ProblemsController.php(24): App\Services\ProblemsService->getOne('subject') #5 [internal function]: App\Controllers\ProblemsController->getOne('subject') #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-09 01:09:11] application.DEBUG: < 500 [] []
[2018-01-09 01:09:17] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:09:17] application.ERROR: No route found for "GET /api/v1/problems/subject/" [] []
[2018-01-09 01:09:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:09:17] application.DEBUG: < 404 [] []
[2018-01-09 01:09:31] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_","route_parameters":{"_controller":"problems.controller:getAllSet","_route":"GET_api_v1_problems_subject_"},"request_uri":"http://localhost:9001/api/v1/problems/subject/","method":"GET"} []
[2018-01-09 01:09:31] application.DEBUG: > GET /api/v1/problems/subject/ [] []
[2018-01-09 01:09:31] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$subject_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$subject_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:09:31] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$subject_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:09:31] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:09:31] application.DEBUG: < 500 [] []
[2018-01-09 01:09:54] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"{1}","_route":"GET_api_v1_problems_subject_subject_id_"},"request_uri":"http://localhost:9001/api/v1/problems/subject/%7B1%7D/","method":"GET"} []
[2018-01-09 01:09:54] application.DEBUG: > GET /api/v1/problems/subject/%7B1%7D/ [] []
[2018-01-09 01:09:54] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$topic_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$topic_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:09:54] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$topic_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:09:54] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:09:54] application.DEBUG: < 500 [] []
[2018-01-09 01:10:28] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:10:28] application.ERROR: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:10:28] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:10:28] application.DEBUG: < 404 [] []
[2018-01-09 01:10:46] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type/1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type/1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:10:46] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" [] []
[2018-01-09 01:10:46] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:10:46] application.DEBUG: < 404 [] []
[2018-01-09 01:10:53] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:10:53] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:10:53] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:10:53] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:10:53] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:10:53] application.DEBUG: < 500 [] []
[2018-01-09 01:11:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type/1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type/1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:11:15] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" [] []
[2018-01-09 01:11:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:11:15] application.DEBUG: < 404 [] []
[2018-01-09 01:11:21] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:11:21] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:11:21] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:11:21] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:11:21] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:11:21] application.DEBUG: < 500 [] []
[2018-01-09 01:12:35] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"{1}","topic_id":"{1}","type_id":"{1}","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D","method":"GET"} []
[2018-01-09 01:12:35] application.DEBUG: > GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D [] []
[2018-01-09 01:12:35] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:12:35] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:12:35] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:12:35] application.DEBUG: < 500 [] []
[2018-01-09 01:15:19] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:15:19] application.ERROR: No route found for "GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D/" [] []
[2018-01-09 01:15:19] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:15:19] application.DEBUG: < 404 [] []
[2018-01-09 01:15:32] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"{1}","topic_id":"{1}","type_id":"{1}","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D","method":"GET"} []
[2018-01-09 01:15:32] application.DEBUG: > GET /api/v1/problems/subject/%7B1%7D/topic/%7B1%7D/type/%7B1%7D [] []
[2018-01-09 01:15:32] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:15:32] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:15:32] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:15:32] application.DEBUG: < 500 [] []
[2018-01-09 01:16:34] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:16:34] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:16:34] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:16:34] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:16:34] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:16:34] application.DEBUG: < 500 [] []
[2018-01-09 01:16:44] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type/1/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type/1/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:16:44] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type/1/" [] []
[2018-01-09 01:16:44] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:16:44] application.DEBUG: < 404 [] []
[2018-01-09 01:16:48] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:16:48] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:16:48] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:16:48] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:16:48] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:16:48] application.DEBUG: < 500 [] []
[2018-01-09 01:20:09] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:20:09] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:20:09] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:20:09] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:20:09] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:20:09] application.DEBUG: < 500 [] []
[2018-01-09 01:20:13] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:20:13] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type" [] []
[2018-01-09 01:20:13] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:20:13] application.DEBUG: < 404 [] []
[2018-01-09 01:20:18] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /api/v1/problems/subject/1/topic/1/type/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/v1/problems/subject/1/topic/1/type/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/problems/subject/1/topic/1/type/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 01:20:18] application.ERROR: No route found for "GET /api/v1/problems/subject/1/topic/1/type/" [] []
[2018-01-09 01:20:18] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 01:20:18] application.DEBUG: < 404 [] []
[2018-01-09 01:20:27] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:20:27] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:20:27] application.CRITICAL: RuntimeException: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\ProblemsController::getAllSet()\" requires that you provide a value for the \"$problem_type_id\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 01:20:27] application.ERROR: Controller "App\Controllers\ProblemsController::getAllSet()" requires that you provide a value for the "$problem_type_id" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 01:20:27] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(428): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(324): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(190): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 01:20:27] application.DEBUG: < 500 [] []
[2018-01-09 01:21:05] application.INFO: Matched route "{route}". {"route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_problem_type_id","route_parameters":{"_controller":"problems.controller:getAllSet","subject_id":"1","topic_id":"1","problem_type_id":"1","_route":"GET_api_v1_problems_subject_subject_id_topic_topic_id_type_problem_type_id"},"request_uri":"http://localhost:9001/api/v1/problems/subject/1/topic/1/type/1","method":"GET"} []
[2018-01-09 01:21:05] application.DEBUG: > GET /api/v1/problems/subject/1/topic/1/type/1 [] []
[2018-01-09 01:21:05] application.DEBUG: < 200 [] []
[2018-01-09 13:39:36] application.INFO: Matched route "{route}". {"route":"GET_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:getAll","_route":"GET_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"GET"} []
[2018-01-09 13:39:36] application.DEBUG: > GET /api/v1/subjects [] []
[2018-01-09 13:39:36] application.DEBUG: < 200 [] []
[2018-01-09 16:04:20] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:04:20] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:04:20] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:04:20] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:04:20] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:04:20] application.DEBUG: < 500 [] []
[2018-01-09 16:13:31] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:13:31] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:13:31] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:13:31] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:13:31] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:13:31] application.DEBUG: < 500 [] []
[2018-01-09 16:14:02] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:14:02] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:14:02] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:14:02] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:14:02] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:14:02] application.DEBUG: < 500 [] []
[2018-01-09 16:14:10] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/stackproblems/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/stackproblems/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/stackproblems/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 16:14:10] application.ERROR: No route found for "POST /api/v1/stackproblems/" [] []
[2018-01-09 16:14:10] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 16:14:10] application.DEBUG: < 404 [] []
[2018-01-09 16:14:36] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/stackproblems/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/stackproblems/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/stackproblems/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 16:14:36] application.ERROR: No route found for "POST /api/v1/stackproblems/" [] []
[2018-01-09 16:14:36] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 16:14:36] application.DEBUG: < 404 [] []
[2018-01-09 16:14:41] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /api/v1/stackproblems/" (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /api/v1/stackproblems/\" at /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/api/v1/stackproblems/\". at /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2018-01-09 16:14:41] application.ERROR: No route found for "POST /api/v1/stackproblems/" [] []
[2018-01-09 16:14:41] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #7 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #11 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #12 {main} [] []
[2018-01-09 16:14:41] application.DEBUG: < 404 [] []
[2018-01-09 16:14:53] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:14:53] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:14:53] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:14:53] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:14:53] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:14:53] application.DEBUG: < 500 [] []
[2018-01-09 16:16:11] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:16:11] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:16:11] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:16:11] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:16:11] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:16:11] application.DEBUG: < 500 [] []
[2018-01-09 16:21:35] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:21:35] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:21:35] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:21:35] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:21:35] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:21:35] application.DEBUG: < 500 [] []
[2018-01-09 16:22:34] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:22:34] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:22:34] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:22:34] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:22:34] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:22:34] application.DEBUG: < 500 [] []
[2018-01-09 16:24:41] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:24:41] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 16:24:41] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 16:24:41] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 16:24:41] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 16:24:41] application.DEBUG: < 500 [] []
[2018-01-09 16:28:49] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 16:28:49] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 18:20:35] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 18:20:35] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 18:20:35] application.CRITICAL: RuntimeException: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. (uncaught exception) at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php line 82 {"exception":"[object] (RuntimeException(code: 0): Controller \"App\\Controllers\\StackProblemsController::processAnswer2()\" requires that you provide a value for the \"$request\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. at /var/www/html/vendor/symfony/http-kernel/Controller/ArgumentResolver.php:82)"} []
[2018-01-09 18:20:35] application.ERROR: Controller "App\Controllers\StackProblemsController::processAnswer2()" requires that you provide a value for the "$request" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one. [] []
[2018-01-09 18:20:35] application.ERROR: #0 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\Controller\ArgumentResolver->getArguments(Object(Symfony\Component\HttpFoundation\Request), Array) #1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #2 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #3 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(471): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #5 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #6 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(186): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #7 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #8 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #9 {main} [] []
[2018-01-09 18:20:35] application.DEBUG: < 500 [] []
[2018-01-09 18:28:08] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 18:28:08] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 18:37:44] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 18:37:44] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 18:38:52] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 18:38:52] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 20:09:36] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 20:09:36] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 20:16:22] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 20:16:22] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 20:18:24] application.INFO: Matched route "{route}". {"route":"POST_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:save","_route":"POST_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"POST"} []
[2018-01-09 20:18:24] application.DEBUG: > POST /api/v1/subjects [] []
[2018-01-09 20:18:26] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO subject (subject_id, subject_name) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO subject (subject_id, subject_name) VALUES (?, ?)' with params [null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 20:18:26] application.ERROR: An exception occurred while executing 'INSERT INTO subject (subject_id, subject_name) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null [] []
[2018-01-09 20:18:26] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sub...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sub...', Array, Array) #3 /var/www/html/src/App/Services/SubjectsService.php(26): Doctrine\DBAL\Connection->insert('subject', Array) #4 /var/www/html/src/App/Controllers/SubjectsController.php(37): App\Services\SubjectsService->save(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\SubjectsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-09 20:18:26] application.DEBUG: < 500 [] []
[2018-01-09 20:20:34] application.INFO: Matched route "{route}". {"route":"POST_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:save","_route":"POST_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"POST"} []
[2018-01-09 20:20:34] application.DEBUG: > POST /api/v1/subjects [] []
[2018-01-09 20:20:34] application.DEBUG: < 200 [] []
[2018-01-09 20:27:59] application.INFO: Matched route "{route}". {"route":"POST_api_v1_subjects","route_parameters":{"_controller":"subjects.controller:save","_route":"POST_api_v1_subjects"},"request_uri":"http://localhost:9001/api/v1/subjects","method":"POST"} []
[2018-01-09 20:27:59] application.DEBUG: > POST /api/v1/subjects [] []
[2018-01-09 20:27:59] application.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO subject (subject_name, subject_photo) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO subject (subject_name, subject_photo) VALUES (?, ?)' with params [null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 20:27:59] application.ERROR: An exception occurred while executing 'INSERT INTO subject (subject_name, subject_photo) VALUES (?, ?)' with params [null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'subject_name' cannot be null [] []
[2018-01-09 20:27:59] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sub...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sub...', Array, Array) #3 /var/www/html/src/App/Services/SubjectsService.php(26): Doctrine\DBAL\Connection->insert('subject', Array) #4 /var/www/html/src/App/Controllers/SubjectsController.php(37): App\Services\SubjectsService->save(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\SubjectsController->save(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-09 20:27:59] application.DEBUG: < 500 [] []
[2018-01-09 20:28:29] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems","route_parameters":{"_controller":"stackProblems.controller:processAnswer2","_route":"POST_api_v1_stackproblems"},"request_uri":"http://localhost:9001/api/v1/stackproblems","method":"POST"} []
[2018-01-09 20:28:29] application.DEBUG: > POST /api/v1/stackproblems [] []
[2018-01-09 20:28:29] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params ["1", "1", "1"]:  SQLSTATE[HY000]: General error: 1364 Field 'resume_id' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params [\"1\", \"1\", \"1\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'resume_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'resume_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'resume_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-09 20:28:29] application.ERROR: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params ["1", "1", "1"]:  SQLSTATE[HY000]: General error: 1364 Field 'resume_id' doesn't have a default value [] []
[2018-01-09 20:28:29] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO his...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO his...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(64): Doctrine\DBAL\Connection->insert('history', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(68): App\Services\StackProblemsService->addHistory(Array) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->processAnswer2(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-09 20:28:29] application.DEBUG: < 500 [] []
