[2018-01-11 00:43:56] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:43:56] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:48:24] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:48:24] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:48:24] application.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, correct) VALUES (?, ?, ?)' with params ["2", "1", "1"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'correct' in 'field list' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO history (problem_id, student_id, correct) VALUES (?, ?, ?)' with params [\"2\", \"1\", \"1\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'correct' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'correct' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'correct' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-11 00:48:24] application.ERROR: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, correct) VALUES (?, ?, ?)' with params ["2", "1", "1"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'correct' in 'field list' [] []
[2018-01-11 00:48:24] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO his...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO his...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(76): Doctrine\DBAL\Connection->insert('history', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(42): App\Services\StackProblemsService->addHistory(Array) #5 /var/www/html/src/App/Controllers/StackProblemsController.php(62): App\Controllers\StackProblemsController->updateHistory(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-11 00:48:24] application.DEBUG: < 500 [] []
[2018-01-11 00:49:14] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:49:14] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:49:14] application.CRITICAL: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params ["2", "1", "1"]:  SQLSTATE[HY000]: General error: 1364 Field 'history_id' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params [\"2\", \"1\", \"1\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'history_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'history_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'history_id' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-11 00:49:14] application.ERROR: An exception occurred while executing 'INSERT INTO history (problem_id, student_id, history_answer) VALUES (?, ?, ?)' with params ["2", "1", "1"]:  SQLSTATE[HY000]: General error: 1364 Field 'history_id' doesn't have a default value [] []
[2018-01-11 00:49:14] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO his...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO his...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(76): Doctrine\DBAL\Connection->insert('history', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(42): App\Services\StackProblemsService->addHistory(Array) #5 /var/www/html/src/App/Controllers/StackProblemsController.php(62): App\Controllers\StackProblemsController->updateHistory(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-11 00:49:14] application.DEBUG: < 500 [] []
[2018-01-11 00:51:03] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:51:03] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:53:00] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:53:00] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:53:36] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:53:36] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:55:05] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:55:05] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:56:44] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:56:44] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:56:45] application.CRITICAL: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT * FROM stack_problem WHERE  done = 0 AND student_id =  order by stack_problem_id limit 1':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by stack_problem_id limit 1' at line 1 (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT * FROM stack_problem WHERE  done = 0 AND student_id =  order by stack_problem_id limit 1':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by stack_problem_id limit 1' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by stack_problem_id limit 1' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by stack_problem_id limit 1' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2018-01-11 00:56:45] application.ERROR: An exception occurred while executing 'SELECT * FROM stack_problem WHERE  done = 0 AND student_id =  order by stack_problem_id limit 1':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by stack_problem_id limit 1' at line 1 [] []
[2018-01-11 00:56:45] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM s...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(766): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM s...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(26): Doctrine\DBAL\Connection->fetchAll('SELECT * FROM s...') #4 /var/www/html/src/App/Controllers/StackProblemsController.php(65): App\Services\StackProblemsService->getFirst(NULL) #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-11 00:56:45] application.DEBUG: < 500 [] []
[2018-01-11 00:58:09] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:58:09] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:58:10] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM student_id WHERE student_id = ?' with params ["1"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.student_id' doesn't exist (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'DELETE FROM student_id WHERE student_id = ?' with params [\"1\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.student_id' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.student_id' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.student_id' doesn't exist at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-11 00:58:10] application.ERROR: An exception occurred while executing 'DELETE FROM student_id WHERE student_id = ?' with params ["1"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'id4147366_vestapp.student_id' doesn't exist [] []
[2018-01-11 00:58:10] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM stu...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM stu...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(31): Doctrine\DBAL\Connection->delete('student_id', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(65): App\Services\StackProblemsService->getFirst('1') #5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #7 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #8 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #14 {main} [] []
[2018-01-11 00:58:10] application.DEBUG: < 500 [] []
[2018-01-11 00:59:09] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 00:59:09] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 00:59:09] application.DEBUG: < 200 [] []
[2018-01-11 00:59:57] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_initialize","route_parameters":{"_controller":"stackProblems.controller:initialize","_route":"POST_api_v1_stackproblems_initialize"},"request_uri":"http://localhost:9001/api/v1/stackproblems/initialize","method":"POST"} []
[2018-01-11 00:59:57] application.DEBUG: > POST /api/v1/stackproblems/initialize [] []
[2018-01-11 00:59:58] application.DEBUG: < 200 [] []
[2018-01-11 01:00:51] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:00:51] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:00:52] application.DEBUG: < 200 [] []
[2018-01-11 01:12:05] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:12:05] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:12:06] application.DEBUG: < 200 [] []
[2018-01-11 01:13:13] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:13:13] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:13:13] application.CRITICAL: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "3", 1, "1"]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1-1-1' for key 'problem_student_idx' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"3\", 1, \"1\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1-1-1' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1-1-1' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1-1-1' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-11 01:13:13] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "3", 1, "1"]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-1-1-1' for key 'problem_student_idx' [] []
[2018-01-11 01:13:13] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(105): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(56): App\Services\StackProblemsService->addToStackEnd(Array) #5 /var/www/html/src/App/Controllers/StackProblemsController.php(63): App\Controllers\StackProblemsController->updateStack(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-11 01:13:13] application.DEBUG: < 500 [] []
[2018-01-11 01:15:19] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:15:19] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:15:19] application.DEBUG: < 200 [] []
[2018-01-11 01:15:25] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:15:25] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:15:25] application.DEBUG: < 200 [] []
[2018-01-11 01:15:34] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:15:34] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:15:34] application.DEBUG: < 200 [] []
[2018-01-11 01:16:13] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:16:13] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:16:14] application.DEBUG: < 200 [] []
[2018-01-11 01:18:00] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:18:00] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:18:00] application.DEBUG: < 200 [] []
[2018-01-11 01:18:51] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:18:51] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:18:51] application.DEBUG: < 200 [] []
[2018-01-11 01:20:06] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:20:06] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:20:07] application.CRITICAL: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "6", 1, "0"]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1-1-0' for key 'problem_student_idx' (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params [\"1\", \"6\", 1, \"0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1-1-0' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1-1-0' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1-1-0' for key 'problem_student_idx' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-11 01:20:07] application.ERROR: An exception occurred while executing 'INSERT INTO stack_problem (student_id, problem_id, done, correct) VALUES (?, ?, ?, ?)' with params ["1", "6", 1, "0"]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1-1-0' for key 'problem_student_idx' [] []
[2018-01-11 01:20:07] application.ERROR: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sta...', Array) #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sta...', Array, Array) #3 /var/www/html/src/App/Services/StackProblemsService.php(105): Doctrine\DBAL\Connection->insert('stack_problem', Array) #4 /var/www/html/src/App/Controllers/StackProblemsController.php(54): App\Services\StackProblemsService->addToStackEnd(Array) #5 /var/www/html/src/App/Controllers/StackProblemsController.php(64): App\Controllers\StackProblemsController->updateStack(Object(Symfony\Component\HttpFoundation\Request)) #6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): App\Controllers\StackProblemsController->getNextFromStack(Object(Symfony\Component\HttpFoundation\Request)) #7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /var/www/html/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(462): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #10 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(234): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true) #11 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(251): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true) #12 /var/www/html/vendor/symfony/http-kernel/HttpCache/HttpCache.php(177): Symfony\Component\HttpKernel\HttpCache\HttpCache->invalidate(Object(Symfony\Component\HttpFoundation\Request), true) #13 /var/www/html/vendor/silex/silex/src/Silex/Provider/HttpCache/HttpCache.php(35): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 /var/www/html/web/index.php(13): Silex\Provider\HttpCache\HttpCache->run() #15 {main} [] []
[2018-01-11 01:20:07] application.DEBUG: < 500 [] []
[2018-01-11 01:21:49] application.INFO: Matched route "{route}". {"route":"POST_api_v1_stackproblems_getnextfromstack","route_parameters":{"_controller":"stackProblems.controller:getNextFromStack","_route":"POST_api_v1_stackproblems_getnextfromstack"},"request_uri":"http://localhost:9001/api/v1/stackproblems/getnextfromstack","method":"POST"} []
[2018-01-11 01:21:49] application.DEBUG: > POST /api/v1/stackproblems/getnextfromstack [] []
[2018-01-11 01:21:49] application.DEBUG: < 200 [] []
